version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestP14Project
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testp14.integrations:testEdge
  packages:
  - name: TestP14Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2023
